name: Build and Push Docker Image to GitHub Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
  # The container is built for the toolchains used in Kunai
  # and with the latest (at build time) version of bpf-linker.
  # Creating a new image every week seems a reasonable trade-off
  # to ensure up to date build tools
  schedule:
    - cron: "37 13 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kunai-builder:latest
